apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
  - name: db
    image: 678092784151.dkr.ecr.us-east-1.amazonaws.com/myrepo_clo835:mydb
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
