apiVersion: v1
kind: Namespace
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
    
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
